### ISSUE TITLE
Adding support of Project Amber in CoCo

### ISSUE THREAD

**Issue by peterzcst** [confidential-containers/documentation#120]
[Project Amber](https://www.intel.com/content/www/us/en/security/project-amber.html) is the code name for Intel’s groundbreaking service/SaaS-based implementation of an independent trust authority that provides attestation of workloads in a public/private multi-cloud environment.

Designed to remotely verify and assert trustworthiness of compute assets such as Trusted Execution Environments (TEEs), devices, Roots of Trust, and more, the service is operationally independent from the Cloud/Edge infrastructure provider hosting the confidential computing workloads. 

We would like add support of Project Amber as a production ready 3rd party Remote attestation service in CoCo.  It's win-win for both CoCo and project Amber to bring more potential end users and customer to both sides. 

The architecture is as below :
<img width="650" alt="image" src="https://user-images.githubusercontent.com/94910408/234199489-1dd42703-10ec-4884-a1a4-4c758531aed4.png">

This is fully compatible with current CoCo design.

**Comment by tnakaike** [comment]
@peterzcst Hello, this is an interesting proposal.

I have one question. What type of evidence is covered by Amber attestation service? Do you suppose to use tdx or sgx evidence implemented [here](https://github.com/confidential-containers/attestation-agent/tree/main/attester/src)?

**Comment by sameo** [comment]
@tnakaike fwiw there's a pending PR for Amber integration with KBS at https://github.com/confidential-containers/kbs/pull/77
