### ISSUE TITLE
Need project glossary

### ISSUE THREAD

**Issue by jodh-intel** [confidential-containers/documentation#13]
This project uses a *lot* of acronyms and abbreviations. It needs a glossary that specifies:

- The full name of the acronym/abbreviation.
- A one sentence example of each term.
- An optional link to either a canonical source reference document or a document in one of this GitHub organisations repo's.

I'd suggest enabling the wiki in this repo and creating a template (https://github.com/kata-containers/kata-containers/blob/main/Glossary.md seems as good as any), advertising it and getting all contributors to this organisation to hack on the wiki page for a couple of weeks. The resulting file can then be cleaned up and moved in-tree.

**Comment by jodh-intel** [comment]
Hi @sameo - I don't seem to have the privs to add labels in this repo but this might be a `good first issue` contender?

**Comment by bpradipt** [comment]
> Hi @sameo - I don't seem to have the privs to add labels in this repo but this might be a `good first issue` contender?

added the label @jodh-intel

**Comment by jodh-intel** [comment]
I've made a start on this:

- https://github.com/confidential-containers/documentation/wiki/Glossary

As you'll see, it's currently mostly a bunch of weakly defined acronyms and abbreviations so **please** can everyone help to hack this into a better shape by expanding on terms like KBS and KBC, and adding in all the bits I've missed! :smile:

> **Note:** Please see the note at the top of the glossary pointing to the [Kata glossary](https://github.com/kata-containers/kata-containers/wiki/Glossary). We should avoid duplication where possible.

**Comment by jodh-intel** [comment]
Closing this as we now have an impressively long list of terms and acronyms in:

- https://github.com/confidential-containers/documentation/wiki/Glossary
- https://github.com/confidential-containers/documentation/wiki/Acronyms

However, new terms keeps popping up, so please can the community continue to help maintain these useful documents!
