### ISSUE TITLE
[RFC] merge community repo into documentation repo 

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/documentation#27]
We replicated the kata structure in creating a separate [community repo](https://github.com/confidential-containers/community). 
I'm not sure that's necessary but I don't know what led to a separate community repo in kata.
I think we could just merge the community content into this documentation repo. That would simplify maintenance in having one less repo to deal with and also make it easier for users to have a single place to read about how this project works.

**Comment by fitzthum** [comment]
Hypothetically the documentation repo has technical information about the project while the community repo has information about organization and process of the community. It's true that the community repo has not been very active recently. This might change over the next few weeks as we do the CNCF onboarding stuff. My 2 cents would be to wait until after that process and see if the community repo still feels unnecessary.

**Comment by dcmiddle** [comment]
The community repo has picked up more activity since we moved into CNCF.
