### ISSUE TITLE
First release documentation 

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/documentation#38]
What kind of documentation should we have for our first release? I have three questions.

**What kind of docs should we have for end-users?**
Ideally the operator will be so easy to use that we don't need excessive documentation. We should probably have some basic info in the operator repo. There is already a basic guide there. Let's just make sure that it's updated when we make our release.

**Where should end-users report issues?** 
End-users could run into a wide variety of issues. They often won't be able to identify the most appropriate place to create an issue. Should we setup a clear place for general issues? Where should it be? 

**What about a developer guide?** 
As the project grows, we should make it easier for people to contribute. Do we expect developers to use the operator? We should probably add some instructions for how to switch out various components (or even just a list of what components there are). @stevenhorsman et al have some great [docs](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md) for CCv0. Should we try to adapt this as part of the developer guide?

CC:  @bpradipt @jensfr @magowan @dcmiddle @sameo

**Comment by ariel-adam** [comment]
@fitzthum is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by fitzthum** [comment]
Docs can still be improved but since this explicitly references the first release let's close it. I am working on a developer guide in the background but it might be a while before it's finished.
