### ISSUE TITLE
standardize format of documentation filenames

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/documentation#50]
We have a bunch of different approaches to naming our documentation files. Let's pick one so it looks legit. 

Some options: 

- `README.md`
- `README`
- `readme.md`
- `Readme.md`
- `ReAdMe.Md`
-  `pɯ˙ǝɯpɐǝɹ`

What should we do?

**Comment by bpradipt** [comment]
README.md - default when creating Github project

**Comment by fitzthum** [comment]
> README.md - default when creating Github project

Yeah this basically standard, but I there could be some debate about which other files should be uppercase.

**Comment by fitzthum** [comment]
Ok, having looked around a bit (mainly at various Rust crates), I think we should go with `snake_case` for the documentation files. `README.md` and other files aren't documentation files so they will stay uppercase.

**Comment by fitzthum** [comment]
Fixed by #51
