### ISSUE TITLE
naive question about ebpf

### ISSUE THREAD

**Issue by ramrattle** [confidential-containers/documentation#82]
Is there anyway we can leverage this project to escape ebpf? I mean when I'm running my apps in public or multi tenant cluster I don't want ebpf snooping on my container, any pointers or study on confidential containers + ebpf combination.

**Comment by dcmiddle** [comment]
Hi @ramrattle. Good question. I don't think we have a clear diagram showing this... In Confidential Computing, the host kernel cannot read or write to the memory of the enclave (sgx) or confidential guest (TDX, SEV, etc.). Given that I would say that eBPF does not have any access to the trusted components of CoCo. 
If that clarifies things please let me know and we can close this issue.
If you see some attack though, please describe it.
Thanks
